### ISSUE TITLE
No error handling

### ISSUE THREAD

**Issue by pauldavidgilligan** [alimate/errors-spring-boot-starter#90] opened 2019-10-07 13:37 UTC
Hi! Great project!

Added in the dependency and getting null when trying simple 404 test. I must be doing something very wrong somewhere any ideas?

```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

null

There was an unexpected error (type=null, status=null)

```

**Comment by alimate** [comment] 2019-10-07 18:42
Hey @pauldavidgilligan . Thanks for your compliment and contribution.

By default, Spring Boot registers a default [`BasicErrorController`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/error/BasicErrorController.java) which catches every exception and produces a machine or human-friendly error result. When [calling an API from a browser](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/error/BasicErrorController.java#L86), you would see the whitelabel error which I highly recommend to replace.

As you can spot from the source code, the `BasicErrorController` uses a very special `ErrorProperties` abstraction to exctract the error details. Since we re-define the default `ErrorProperties` with [our version of it](https://github.com/alimate/errors-spring-boot-starter/blob/master/src/main/java/me/alidg/errors/adapter/attributes/ServletErrorAttributes.java) to expose some other set of information, the `BasicErrorController` with HTML clients, would see `null`s all over the place.

**Comment by alimate** [comment] 2019-10-17 11:36
I'm going to close this issue since this is the intended behavior of the library.

**Closed by alimate** 2019-10-17 11:36 UTC
